version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    environment:
      - DATABASE_HOST=pg
      - SECRET_KEY_BASE="DEV-uXie9eigha9raeVainahKaemie3ohPho0Eeji9veizie4OoPeigoox6weto0lee3"
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=DEV-zae5Tu8thay8Eerah8Shu6iemuung2oo
      - DATABASE_DATABASE=decidim_dev
      - RAILS_ENV=development
      - RACK_ENV=development
      - PORT=3000
      - RAILS_MAX_THREADS=1
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - 3000:3000
    depends_on:
      - pg
      - mailer
    networks:
      - private
      - default

  pg:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=DEV-zae5Tu8thay8Eerah8Shu6iemuung2oo
      - POSTGRES_USER=decidim
      - POSTGRES_DB=decidim_dev
    networks:
      - private

  mailer:  
    image: tophfr/mailcatcher
    ports:
      - "1025:1025"
      - "1080:80"
    networks:
      - private
      - default

volumes:
  node_modules: {}
  pg-data: {}
networks:
  private:
    internal: true