########################################################################
# Dependancy layer
# Gem are installed, assets are compiled. All build libraries to compiles
# decidim gems are already installed.
########################################################################
FROM git.octree.ch:4567/decidim/decidim-quickstart/0.23:quickstart-latest  AS build
LABEL maintainer="hello@octree.ch"
ENV RAILS_ENV="development" \
    RACK_ENV="development" \
    RAILS_ROOT="/home/decidim/app"
WORKDIR $RAILS_ROOT

RUN bundle config set without '' && bundle config set with 'development:test:production' 
# Install gems
COPY Gemfile ./Gemfile
COPY Gemfile.lock ./Gemfile.lock
RUN bundle install

# Remove quickstart migrations, and use ours
RUN rm -rf db/migrate
COPY . .

RUN source $NVM_DIR/nvm.sh; nvm use $NODE_VERSION && \
    bundle binstubs --all

ENTRYPOINT [ "./start-dev.sh" ]
CMD ["bundle", "exec", "puma", "-C config/puma.rb"]